import eslint from '@eslint/js'
import { defineConfig } from 'eslint/config'
import tseslint from 'typescript-eslint'
import eslintConfigPrettier from 'eslint-config-prettier/flat'

export default defineConfig(
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
  },
  eslint.configs.recommended,
  tseslint.configs.recommendedTypeChecked,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 0,
      '@typescript-eslint/no-misused-promises': 0,
      '@typescript-eslint/no-unsafe-argument': 0,
      '@typescript-eslint/no-unsafe-assignment': 0,
      '@typescript-eslint/no-unnecessary-type-assertion': 0,
      '@typescript-eslint/no-unsafe-call': 0,
      '@typescript-eslint/no-unsafe-member-access': 0,
      '@typescript-eslint/no-unsafe-return': 0,
      '@typescript-eslint/prefer-promise-reject-errors': 0,
      '@typescript-eslint/unbound-method': 0,
      '@typescript-eslint/no-unused-vars': [
        2,
        { argsIgnorePattern: '^_', ignoreRestSiblings: true, args: 'none' },
      ],
      '@typescript-eslint/prefer-readonly': 1,
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'array-callback-return': 1,
      'arrow-body-style': 0,
      'block-scoped-var': 2,
      camelcase: 0,
      'class-methods-use-this': 0,
      'consistent-return': 0,
      'constructor-super': 2,
      'default-case': 0,
      'dot-location': [2, 'property'],
      'dot-notation': 2,
      eqeqeq: [2, 'smart'],
      'func-names': 0,
      'func-style': [2, 'declaration', { allowArrowFunctions: true }],
      'function-paren-newline': 0,
      'global-require': 0,
      'jsx-quotes': [2, 'prefer-double'],
      'linebreak-style': 2,
      'lines-between-class-members': 0,
      'max-classes-per-file': 0,
      'new-cap': 0,
      'new-parens': 2,
      'no-alert': 0,
      'no-case-declarations': 0,
      'no-class-assign': 2,
      'no-confusing-arrow': 2,
      'no-console': 0,
      'no-constant-condition': 1,
      'no-duplicate-imports': 2,
      'no-eval': 2,
      'no-extend-native': 2,
      'no-extra-label': 2,
      'no-fallthrough': 2,
      'no-implied-eval': 2,
      'no-inner-declarations': 0,
      'no-invalid-this': 0,
      'no-label-var': 2,
      'no-lone-blocks': 2,
      'no-lonely-if': 2,
      'no-loop-func': 2,
      'no-mixed-operators': 0,
      'no-multi-assign': 0,
      'no-nested-ternary': 0,
      'no-new-object': 2,
      'no-param-reassign': 0,
      'no-plusplus': 0,
      'no-self-compare': 2,
      'no-shadow': 0,
      'no-shadow-restricted-names': 2,
      'no-tabs': 2,
      'no-underscore-dangle': 0,
      'no-unexpected-multiline': 2,
      'no-unmodified-loop-condition': 2,
      'no-unneeded-ternary': 2,
      'no-unused-expressions': 0, // avoid errors on chai expressions
      'no-use-before-define': 0,
      'no-useless-call': 2,
      'no-useless-computed-key': 2,
      'no-useless-concat': 2,
      'no-useless-constructor': 2,
      'no-useless-rename': 2,
      'no-useless-return': 2,
      'no-var': 0,
      'object-shorthand': 0,
      'one-var': 0,
      'operator-assignment': 2,
      'prefer-const': [1, { destructuring: 'all' }],
      'prefer-object-spread': 0,
      'prefer-promise-reject-errors': [2, { allowEmptyReject: true }],
      'prefer-spread': 0,
      'prefer-template': 0,
      radix: 2,
      'valid-jsdoc': 0,
      yoda: 2,
    },
  },
  eslintConfigPrettier,
)
